#!/usr/bin/env python3
"""Render the natural-video/compositional follow-up from result JSON."""
from pathlib import Path
import subprocess,sys
import json
R=Path(__file__).resolve().parents[1]/"results/followup"
load=lambda p:json.loads((R/p).read_text())
n=load("natural_video.json");v=load("verified_negative_retrieval.json")["result"];a=load("active_acquisition.json")["result"];s=load("sugarcrepe.json")
f=lambda x:f"{100*x:.2f}%";ci=lambda x:f"[{f(x[0])}, {f(x[1])}]"
lines=["# Natural-Video and Compositional Follow-up","","Generated by `scripts/render_followup_report.py` from machine-readable results.","",
"## Natural-video robustness","",f"UCF101 subset: {n['n_decoded']} decoded of {n['n_requested']} requested videos; {len(n['decode_failures'])} failures.","","| Condition | Frozen CLIP top-1 | Corrupted − clean (95% CI) | Temporal − mean top-1 (95% CI) | N_trials |","|---|---:|---:|---:|---:|"]
for c in n["conditions"]:
 d=n["paired_deltas_temporal_minus_mean"][c];robust="reference" if c=="clean" else f(n["zero_shot"][c]["accuracy_delta_from_clean"]["estimate"])+" "+ci(n["zero_shot"][c]["accuracy_delta_from_clean"]["ci95"]);lines.append(f"| {c} | {f(n['zero_shot'][c]['accuracy'])} | {robust} | {f(d['estimate'])} {ci(d['ci95'])} | 5 |")
lines += ["","## Verified-negative retrieval","","| Direction | Metric | Verified mixed − random (95% CI) | N_trials |","|---|---|---:|---:|"]
for direction,md in v["paired_deltas_verified_mixed_minus_random"].items():
 for metric,d in md.items():
  val=f(d['estimate'])+" "+ci(d['ci95']) if metric!="median_rank" else f"{d['estimate']:.2f} [{d['ci95'][0]:.2f}, {d['ci95'][1]:.2f}]"
  lines.append(f"| {direction} | {metric} | {val} | 5 |")
lines += ["","## Multi-objective active acquisition","","| Budget | Random macro accuracy | Disagreement | Composite | Composite − disagreement (95% CI) |","|---:|---:|---:|---:|---:|"]
for b,d in a["budgets"].items():
 m=d["macro_accuracy"];q=m["composite_minus_disagreement"];lines.append(f"| {f(float(b))} | {f(m['random']['mean'])} | {f(m['disagreement']['mean'])} | {f(m['composite']['mean'])} | {f(q['estimate'])} {ci(q['ci95'])} |")
lines += ["","## SugarCrepe compositional evaluation","","| Family | Accuracy | 95% CI | N |","|---|---:|---:|---:|"]
for family in ["add","replace","swap"]:
 d=s["result"][family];lines.append(f"| {family} | {f(d['accuracy'])} | {ci(d['ci95'])} | {d['n']} |")
lines += ["",f"Macro accuracy across the seven detailed perturbation families: {f(s['result']['macro_family_accuracy']['estimate'])}. N_trials=1.","",
"## Interpretation","","The temporal model is accepted only where its paired seed interval excludes zero. Verified negatives are retained as a methodological failure if their retrieval interval is below zero. Multi-objective acquisition is interpreted separately at each preregistered budget. SugarCrepe measures compositional discrimination, not general safety.","",
"## Reproducibility","","Raw UCF101 videos and COCO images remain outside Git. Archive hashes, model identifiers, GPU, seeds, trial predictions, decode failures, and per-example SugarCrepe predictions are stored in the JSON artifacts.",""]
(R/"REPORT.md").write_text("\n".join(lines))
subprocess.run([sys.executable,str(R.parents[1]/"scripts/update_readme_results.py")],check=True)
