#!/usr/bin/env python3
"""Render the six-sequence report exclusively from machine-readable results."""
from pathlib import Path
import json

ROOT=Path(__file__).resolve().parents[1]; D=ROOT/"results/research_sequence"
load=lambda n:json.loads((D/n).read_text())
s1=load("sequence1_unified_benchmark.json"); s2=load("sequence2_reward_model.json")["result"]
s3=load("sequence3_results.json")["result"]; s4=load("sequence4_results.json")["result"]
s5=load("sequence5_results.json")["result"]; s6=load("sequence6_results.json")["result"]
f=lambda x:f"{100*x:.2f}%"
ci=lambda x:f"[{f(x[0])}, {f(x[1])}]"
lines=["# Six-Sequence Multimodal Research Report","","Generated by `scripts/render_research_sequence.py`; do not edit result values by hand.","",
"## 1. Unified quality evidence","","| Modality | Study | Metric | Estimate | 95% CI | N_trials |","|---|---|---:|---:|---:|---:|"]
for r in s1["evidence"]:
    c="not supplied" if r["ci95"] is None else ci(r["ci95"])
    lines.append(f"| {r['modality']} | {r['study']} | {r['metric']} | {f(r['estimate'])} | {c} | {r['n_trials']} |")
lines += ["","Unlike metrics are not pooled. The shared result is a provenance-preserving evidence layer, not a synthetic cross-modal score.","",
"## 2. Preference reward model","",f"On {s2['n_pairs']} non-tie human preference pairs, the learned five-fold model reached {f(s2['learned']['accuracy'])} accuracy versus {f(s2['handcrafted']['accuracy'])} for the frozen composite. The paired delta was {f(s2['paired_deltas_learned_minus_handcrafted']['accuracy']['estimate'])} (95% CI {ci(s2['paired_deltas_learned_minus_handcrafted']['accuracy']['ci95'])}; N_trials=5). The interval crosses zero. Brier score changed from {s2['handcrafted']['brier']:.4f} to {s2['learned']['brier']:.4f}.","",
"## 3. Controlled temporal evaluation","","| Trajectory | Rank-1 frame 0 | Rank-1 frame 7 | Loss | Embedding drift | N |","|---|---:|---:|---:|---:|---:|"]
for k,v in s3.items(): lines.append(f"| {k} | {f(v['frames'][0]['recall_at_1'])} | {f(v['frames'][-1]['recall_at_1'])} | {f(v['rank1_retention_frame0_minus_frame7'])} | {v['mean_embedding_drift']:.4f} | {v['n_sequences']} |")
lines += ["","These are synthetic eight-frame trajectories over real COCO images, not natural-video estimates.","",
"## 4. Active correction with retraining","","Positive values favor targeted correction for accuracy; negative values favor targeted correction for ECE.","","| Budget | Task | Accuracy delta (95% CI) | ECE delta (95% CI) | Worst-slice accuracy delta (95% CI) |","|---:|---|---:|---:|---:|"]
for b,bd in s4["budgets"].items():
    for task,v in bd.items():
        m=v["metrics"]; lines.append(f"| {f(float(b))} | {task} | {f(m['accuracy']['estimate'])} {ci(m['accuracy']['ci95'])} | {f(m['ece']['estimate'])} {ci(m['ece']['ci95'])} | {f(m['worst_slice_accuracy']['estimate'])} {ci(m['worst_slice_accuracy']['ci95'])} |")
lines += ["","## 5. Hard-negative retrieval","","| Direction | Metric | Hard − random | 95% CI | N_trials |","|---|---|---:|---:|---:|"]
for direction,md in s5["paired_deltas_hard_minus_random"].items():
    for metric,v in md.items():
        display=f"{v['estimate']:.2f}" if metric=="median_rank" else f(v['estimate'])
        c=f"[{v['ci95'][0]:.2f}, {v['ci95'][1]:.2f}]" if metric=="median_rank" else ci(v['ci95'])
        lines.append(f"| {direction} | {metric} | {display} | {c} | 5 |")
lines += ["","Hard-only mining failed decisively. Frozen CLIP neighbors are frequently semantically compatible captions, so treating every nearest non-pair as a negative introduces false-negative supervision.","",
"## 6. Robustness audit","",f"At frame 7, occlusion reduced retrieval Recall@1 to {f(s6['retrieval']['occlusion']['frame7']['recall_at_1'])}, with a {f(s6['retrieval']['occlusion']['flip_rate_from_frame0'])} top-result flip rate. A negated caption scored at least as highly as the original on {f(s6['caption_attacks']['negation_preferred_over_original_rate'])} of examples; subject-count swaps did so on {f(s6['caption_attacks']['count_swap_preferred_over_original_rate'])} (n={s6['caption_attacks']['n']}). This is a controlled audit, not a safety certification.","",
"## Bottom line","","The strongest positive result is that disagreement targeting improves downstream classification after actual retraining, especially for human presence and subject count. The strongest failure result is that naïve hard-negative mining catastrophically damages retrieval. Controlled corruption exposes substantial negation blindness and occlusion sensitivity. Natural-video validation remains the next required external-data step.",""]
(D/"REPORT.md").write_text("\n".join(lines))
